workflows:
  android-debug-build:
    name: 安卓Debug包构建
    max_build_duration: 60
    environment:
      java: 17
    scripts:
      - name: 配置SDK路径
        script: echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      - name: 赋予执行权限
        script: chmod +x gradlew
      - name: 编译Debug APK
        script: ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/*.apk

